language: node_js
sudo: required
dist: trusty
node_js:
  - lts/*
env:
  - BROWSER=ChromeHeadless
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run coveralls
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
